README.md

Made complete table of content  for all info for easy navigation as it was really confusing . Also added alternative method to work on GitHub repository. 
#15

Added table of contents and alternative method

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.js
client/src/components/Header/Header.js
client/src/components/index.js
client/tailwind.config.js
controllers/customerController.js
controllers/productController.js
index.js
models/productSchema.js
package-lock.json
package.json
routes/productRoutes.js

Added searchProduct and filterProduct controller to the Product controllers.

Artigaund search filter controller added

---

controllers/cartController.js
controllers/customerController.js
models/cartSchema.js
models/productSchema.js
package-lock.json
package.json
routes/customerRoutes.js
utils/jwtToken.js

@Trisha-tech 
i have added routes and models 
check it now 
let me know if any improvements need

Added cart routes and models

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/Components/Product.jsx
client/src/Components/SignUpPage.jsx
package-lock.json
package.json

Faults in signup design have been adjusted

adjusted signup

---

controllers/productController.js
models/productSchema.js
routes/productRoutes.js

This commit implements the functionality to  manage shareable links for products in the application. It introduces a new field shareableLink in the Product model and establishes routes and controllers to handle setting and retrieving shareable links for products.
Details of Changes:
Product Model Modification: Added a new field shareableLink to the Product model schema to store shareable links for products.
Controller Functionality: Implemented new controller functions to set and retrieve shareable links for products.
Route Configuration: Created new route in the product routes file to map to the controller functions for managing shareable links.

created route and controller for setting shareable link in Product

---

controllers/customerController.js
models/customerSchema.js
package-lock.json
package.json
routes/productRoutes.js

Now signup works correctly i have checked .
fix #70
fix #71 disposable email functionality created

fix: #70 signup validation and corrected missing import of sharable link

---

client/src/Pages/SignUpPage.jsx
controllers/customerController.js
routes/productRoutes.js

after succesful registration redirecting to login page

Redirecting signup login

---

controllers/adminController.js
controllers/customerController.js
index.js
middlewares/auth.js
models/feebackSchema.js
routes/adminRoutes.js
routes/customerRoutes.js

Added customer feedback and complaint routes, and admin can check, retrieve, and update feedback. Added function to get mail whenever user makes complaint 
Let me know what can be improved

Added customer feedback routes

---

client/src/Components/Footer/Footer.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Pages/SignUpPage.jsx
client/src/index.css

fix #89 
fix #87 
I have fixed the tailwind configuration that was missing from index.css Now tailwind styles are correctly applying and made a responsive Navbar and Footer
here how it is

fixing Tailwind configration and styled Navbar and footer

---

client/package-lock.json
client/src/App.js
client/src/index.js
package-lock.json
package.json

Unwanted imports and wrongly written routes were causing the build fail. I have fixed the routing in this pull request . Please refer to the issue #99 for the same as it was urgent i have created the issue and also the pull request. @Trisha-tech please review and merge

issue#99 Build fail along with bad coding errors 

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/Header/Header.js
client/src/components/HomePage.js
client/src/components/Profile/ProfilePage.js
client/src/components/index.js
client/src/index.js
package-lock.json

Build error is fixed which was coming after the merge operation, there were 2 navbar, removed one navbar and footer was only added on home page, now its coming in all the pages.

Build error fixed ,removed one navbar and footer is added in all pages

---

.github/workflows/ISSUE_TEMPLATE/bug_report.md
.github/workflows/ISSUE_TEMPLATE/feature_request.md

Fixes #111 
@Trisha-tech Please review the PR and merge it if it is good to go

Added Issue Template

---

CONTRIBUTING.md

Added guideline in Contributing file.

---

.github/workflows/autocomment-pr-merge.yml
.github/workflows/autocomment-pr-raise.yml

Created autocomment-pr-merge.yml

---

.github/workflows/close-old-issue.yml

Fixes #121
@Trisha-tech Please review my PR and merge it if it is good to go

Added workflow for closing old issues

---

.github/workflows/close-old-pr.yml

Fixes #122 
@Trisha-tech Please review my PR and merge it if it is good to go

Added workflow for closing old PRs 

---

README.md

Added contributors images

---

.github/Pull_Request_Template.md

Updated the Pr template.
Fixes:  #(issue no.)
#127

docs: updated pr template

---

Dockerfile
client/Dockerfile
package-lock.json

This PR adds Dockerfiles for both the Express server and React client applications. This will allow for easier deployment and consistent environment setup across different environments.
1.Added a Dockerfile for the Express server in the server directory. The Dockerfile sets up the Node.js environment, installs dependencies, and starts the server.
2.Added a Dockerfile for the React client in the client directory. The Dockerfile builds the React application, creates an Nginx container, and serves the built application.
1.Consistent environment setup across different environments (development, staging, production).
2.Easier deployment process by packaging the applications into Docker images.
3.Reduced dependency on specific system configurations or installed software.
4.Improved portability …

Added Dockerfile for server and client setup

---

.env.sample
client/package-lock.json
index.js
package-lock.json
package.json

- Fixes ... connectivity of frontend
- Placeholder: "Fixes #158"

frontend connectivity

---

client/src/Pages/LoginPage.jsx

- Adds ...Added the eye icon to the password field
- Fixes ...
- Updates ...
- Placeholder: "Fixes #148 "
- Added a new feature to the LoginPage
Any additional context or information that reviewers …

Added an Eye icon to the Password field

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Pages/Contact.jsx

Solved Issue #159 
- Adds ... Added the Contact Us Page
- Added a new feature to ... Added the Contact Us Page
[7e01f4dc-dd92-4d78-9e12-26ef674457ab.webm](https://github.com/Trisha-tech/OnlineBookSales/assets/154724111/d05cbc48-d1b0-4f31-9e0a-1aa2e8cf0e54)
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
- [ x] I am working on this issue under GSSOC

Added the contact us page

---

client/src/Pages/Home.jsx

- Adds ...
- Fixes #184  ...
- Updates ...
- Placeholder: "Fixes #184"
- Added a new feature to the Home page...
- This PR is …

Adding Featured Author section

---

client/src/Components/SearchBar.js

- Adds ...
- Fixes #189 
- Updates ...
- Placeholder: "Fixes #189 
- This PR is based on the …

component SearchBar.js continuation- 

---

client/src/Pages/Home.jsx

#189 
- Adds ...
- Fixes #189 
- Updates ...
- Placeholder: "Fixes #189 "
Make sure to check off all the items …

Add a search bar- home.jsx

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Pages/AboutUs.jsx
client/src/Pages/Home.jsx

Solved issue #209 
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
- [ x] I am working on this issue under GSSOC
https://github.com/Trisha-tech/OnlineBookSales/assets/154724111/b9e1d05b-d626-4747-9fcb-0124f42c7ddd

Added the About Us page

---

client/src/App.js
client/src/Pages/Orders.jsx
client/src/Pages/Wishlist.jsx

Closes #218 
- Adds ...
- Fixes #218 
- Updates ...
- Placeholder: "Fixes #123"
Make sure to check off all the …

Corrected all the errors

---

client/src/App.js
client/src/Components/SearchBar.js
client/src/Pages/LoginPage.jsx
client/src/Pages/SignUpPage.jsx
client/src/index.js
client/tailwind.config.js

- Adds ...  Added functionality which prevents page reload on going to signup page (From login page)
- Fixes ... Dark mode implementation in Login and Singup page.
1. Dark mode issue with login and signup pages. 
2. Resolved a bug where whenever we go to signup page (From login page) , it reloads the browser ( which should not happen in a react application ) 
- Updates ... i have updated theme option to implement proper dark mode styles to element when in dark mode
- Placeholder: Fixes #221 
- Added a new feature to ... prevent …

Fixed Dark Mode Issue in Login and Signup Page

---

client/public/index.html

- issue closes #229 
I have created trail effect to the cursor match to the website design them.
https://github.com/user-attachments/assets/bb9b3fd9-fa6a-450f-b707-531cc4269d65
Please take a look and review it.

Added Trail Effect to the Cursor for the Website

---

client/src/Pages/Orders.jsx

- Adds ...
- Fixes ...
- Updates ... The Order Page, to give proper spacing as well as added a message if no active orders are available.
- Placeholder: Fixes #227 
- Refactored the ... Order Page, to give proper spacing as well as added a message if no active orders are available
3. Run `npm test` to execute the test …

Fixed Order Page Frontend UI

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/Components/Footer/Footer.css
client/src/Components/Footer/Footer.jsx
client/src/Pages/PrivacyPolicy.jsx
client/src/index.css

- Issue Fixes #224
I have
- Enhanced and fix the overall `Footer` section
- Added `Hover` `transform` Effects to the Footer links
- Added `Copyright` Section with `dynamic date functionality` which updates yearly 
- Added Legal Section
- Created `Privacy Policy` Page and made it complete responsive using `react styled-components`
- Integrated `preloader` to the privacy policy page.
- Removed the unnecessary `padding` in the App
- Replaced outdated twitter icon with `X icon`
- Added `Social links` for linkedin and Github
https://github.com/user-attachments/assets/67658942-e3f0-4107-9512-77264d8317a7
Please take a look and review it! Thank You!

Enhanced The "Footer" Section. Added "Legal" Section and "Dynamic Copyright" Section

---

client/src/App.js
client/src/Components/GoToTop.jsx

- Issue fixes #236
I have added the Scroll to top button to the website
- Created Scroll to top button using `react styled-components`
- The Button On click scroll back to the top of the page
- It only appears when we scroll down a bit
- Added Hover effects, Base Color`#318CE7` | On Hover `#0269b8` 
- Added `transitions` and `animations` to the button 
https://github.com/user-attachments/assets/6bc7bfca-f921-497b-981a-0cfa741f560d
Please take a look and review it, Thank you!

Added "Scroll to Top" Button Functionality

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Pages/Terms.jsx

- Issue fixes #235
I have created Terms and Conditions Page For the Website 
- Created `Terms.jsx` using react styled-components
- Made it complete responsive 
- Integrated `preloader`
Please take a look and review it! Thank you.

Created Terms and Conditions Page For the Website 

---

client/src/Pages/Contact.jsx

- issue closes #239 
I have made the Contact Us page visually appealing and functional on devices ranging from mobile phones to desktops.

Made Contact Us Page Fully Responsive

---

client/src/index.css

- issue closes #240 
I have enhanced the vertical scrollbar of the website to better align with the overall design theme.
https://github.com/user-attachments/assets/7ac91522-92c9-445d-9441-d4a837568f7e

Enhanced Vertical Scrollbar to Match Website Design Theme

---

client/src/Pages/PrivacyPolicy.jsx
client/src/Pages/Wishlist.jsx

- Adds ...
- Fixes ... The error where on failed fetching, the navbar and footer of wishlist page collapses
- Updates ...
- Placeholder: Fixes #241  
- Fixed a bug in ... Wishlist page where proper spacing was missing 
Add any screenshots that help …

fixed wishlist error

---

client/src/Components/Footer/Footer.css
client/src/Components/Footer/Footer.jsx

- Issue closes #249
I have added the newsletter section to the website 
- Created a `newsletter` section.
- Added `Email validation` .
- Added `client-side validation`.
- Added `thank you for subscribing` message after clicking on submit.
- Made it `responsive`.
https://github.com/user-attachments/assets/345996a4-3faa-4d78-bdde-9806e437883b
Please take a look and review it, thank you!

Add A News Letter Section 

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Pages/Licensing.jsx

- issue closes #245 
I have created the licensing page to the website

Creade Licensing Page to the Website

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Pages/Contributors.css
client/src/Pages/Contributors.jsx

- Issue closes #237
I have added contributors page Please take a look and review it
Also I request you to add level 3 label for this (As per the changes and features I have added and only if you liked it)
https://github.com/user-attachments/assets/64ff9257-91a4-44d2-a112-0ed747773899
Note:
Install these dependencies  
```
npm i axios
```

Create "Our Contributors" Page for the website 

---

client/src/App.js
client/src/Components/CustomerProfile/DeliveryLocation.jsx
client/src/Components/CustomerProfile/Orders.jsx
client/src/Components/CustomerProfile/Profile.jsx
client/src/Components/CustomerProfile/Sidebar.jsx
client/src/Pages/CustomerProfile.jsx

- Adds the Customer Profile page UI.
- Fixes #37
- Updates  UI components for Customer Profile, including Sidebar, Order History, Change Password, and Location settings.
Link any related issues using the format `Fixes #37`. 
There are't any related issue
- Added a new feature to display the Customer Profile page UI.
- Navigation between profile information, orders, and other tabs in sidebar.
Additional Context
- This only fixes the frontend, backend of this part is yet to be added. Please review this PR and suggest any changes if required.

Add Customer Profile UI

---

controllers/adminController.js
controllers/customerController.js
controllers/orderController.js
controllers/productController.js
utils/errorHandler.js
utils/responseHandler.js

Description
This PR does the following:
Enhances the API by adding errorHandler and responseHandler utility functions.
Refactors all API endpoints to use these utility functions for standardized error and success responses.
Related Issues:
Link any related issues using the format Fixes #66 . This helps to automatically close related issues when the PR is merged.
Fixes #66 
Changes
Added errorHandler utility function to handle consistent error responses across APIs.
Added responseHandler utility function to streamline successful API responses.
Refactored all existing API endpoints to use errorHandler for error responses.
Refactored all API success responses to use responseHandler.
Testing …

Enhanced errorHandling and responseHandling.

---

README.md

**### Updated README Structure:**
Added Navigation: A new navigation section was included at the top of the README to enhance user experience. This allows users to quickly navigate to important sections such as Tech Stack, How to Fork, How to Contribute, Code of Conduct, and Contact Information.
Revised Contribution Guide: Clearer instructions were added for contributing to the project, including step-by-step details on how to fork the repository, create new branches, make changes, and submit a pull request.
Included Code of Conduct: A section for the project's Code of Conduct was added, ensuring contributors are aware of community guidelines and acceptable behavior.
Contact Information: A contact section was introduced for any inquiries or support, directing users where they can reach …

Readme file Issue Updation

---

client/src/Pages/Orders.jsx

- Adds ... Sorting options at orders page
- Placeholder: "Fixes #263  "
- Added a new feature to ... sort orders on basis of different options
- This PR is based on the …

added sorting options in order page

---

client/src/Pages/LoginPage.jsx
client/src/Pages/SignUpPage.jsx

I have updated the signup ui as well...
PS: I can also add the login with google feature (frontend).... if you want...

Signup ui updated

---

client/src/Pages/LoginPage.jsx

I have updated the ui of the login page...
OLD UI: 
NEW UI:

login-ui-updated

---

client/src/Pages/Faq.jsx

- Adds Contrasting colors to answer of the faq question in the FAQ Page.

Enhanced the Faq section

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Components/NavBar/NavBar.jsx
client/src/Pages/Cart.jsx

Fixes #290 
I have Enhance the Dark theme of the website
@Trisha-tech  Please Merge this pull request with the labels attached.

Dark Theme of Website Updated Issue no #290 Resolved

---

.vscode/settings.json
client/public/action.html
client/public/fiction.html
client/public/index.html
client/public/manga.html
client/public/philosophy.html
client/public/quiz.html
client/public/tech.html
client/public/thriller.html
index.js

ADDED BOOKS AUTHORS PRICE
- Adds ...
- Fixes ...
- Updates ...
- Placeholder: "Fixes #123"
- This …

ADDED BOOKS AUTHORS PRICE

---

client/public/action.html
client/public/books.html
client/public/fiction.html
client/public/manga.html
client/public/philosophy.html
client/public/quiz.html
client/public/tech.html
client/public/thriller.html
client/src/Components/index.js

i have add box shadow and hover effect in different html file and add curser pointer.
#429 
- Adds ...shadow effect and hover effect
- Fixes ...
- Updates ...shadow effect and hover effect
Link any related issues using the format  #432 . 
- Placeholder: "Fixes #432"
Add any screenshots that help …

add box shadow and hover effect

---

client/src/Components/NavBar/NavBar.jsx

issue : #402 
https://github.com/user-attachments/assets/a40fdb57-2be8-4fc8-b614-d6a8e333da3f

improved navbar for mobile

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/Pages/SignUpPage.jsx
package-lock.json

Added email validation format in sign up page, so that faulty email registration is avoided.
- Placeholder: "Fixes #418 
- [X ] I have performed a self-review of my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
- [ X] I am working on this issue under GSSOC

Add email validation for signup form

---

client/src/Components/AI-BookRecommdation/.gitignore
client/src/Components/AI-BookRecommdation/PREREQUISITES.md
client/src/Components/AI-BookRecommdation/README.md
client/src/Components/AI-BookRecommdation/main.py
client/src/Components/AI-BookRecommdation/requirements.txt
client/src/Components/AI-BookRecommdation/sample.config.toml

A clear and concise description of what the PR does:
- This PR introduces AI-based book recommendations by adding sample book titles to the `config.toml` file.
- Enhances the AI recommendation system by fetching book synopses from Goodreads, improving user interaction and providing engaging book suggestions.
- Refactors the configuration setup to accommodate book metadata for seamless integration with the backend.
- Fixes #343 `Pull_Request`.
List the detailed changes made in this PR:
- Added sample book titles and authors to the `config.toml` file, including:
- **Project Hail Mary** by Andy Weir
- **Home Before Dark** by Riley Sager
- **The Invisible Life of Addie LaRue** by V.E. Schwab
- Refactored backend logic to fetch book synopses from Goodreads based on the book titles provided in …

Added AI-BookRecommdation component

---

index.js

- Adds correct CORS configuration to allow requests from the deployed frontend at `https://book4u-j5au.onrender.com` and also allow for all requests.
- Fixes the CORS error that blocked frontend-backend communication.
- Updates the backend server's CORS policy to support credentials and necessary HTTP methods.
- Fixes #473
- Updated `cors` middleware to allow origins.
- Allowed `GET`, `POST`, `PUT`, `DELETE`, and `OPTIONS` methods for the frontend.
- Ensured that cookies and credentials can be passed from the frontend to the backend.
- This PR is based on resolving the CORS error during frontend-backend communication for the registration page.
Make sure to check …

Update cors origin configuration #473

---

client/src/Components/Footer/Footer.jsx
package-lock.json

**Overview**
This PR does the following:
Updates the hover colors of social icons to reflect their original brand colors.
Fixes #469
List the detailed changes made in this PR:
Changed hover color for LinkedIn icon to #0077B5.
Changed hover color for GitHub icon to #211F1F.
Changed hover color for Instagram icon to #E1306C.
Also apply transition on each icon
Pull this branch.
Run npm install to install dependencies.
Run npm start to start the development server.
Verify that the hover colors for the social icons match their original brand colors:
Hover over the LinkedIn icon and confirm it changes to #0077B5.
Hover over the GitHub icon and confirm it changes to #211F1F.
Hover over the …

Update social icons' hover colors to reflect original brand colors

---

CONTRIBUTING.md

Enhances the full documentation with best code practices, code style guidelines and acknowledgments
Link any related issues using the format `Fixes #501 `. 
- Placeholder: "Fixes #501 "
- Added Best Code Practices
- Added Code Style Guidelines
- Added Acknowledgments
Make sure to check off all the items before submitting. Mark with [x] if …

Enhances With Best Code Practices, Code Style Guidelines And Acknowledgments

---

client/src/Components/NavBar/NavBar.jsx
client/src/Components/SearchBar.js
client/src/Pages/Home.jsx

Implemented Google Books API on search bar
- Adds ...
- Fixes #528 ...
- Updates ...
- Placeholder: "Fixes #528 "
Make sure to check off all the items before submitting. Mark …

[Feature Request]: Implemented Google Books API on search bar

---

client/src/App.js
client/src/Components/Footer/Footer.jsx
client/src/Pages/CancelReturns.jsx

@Trisha-tech 
I have added a page for cancellation and returns successfully
Kindly check it out
https://github.com/user-attachments/assets/dbd76e55-aa4c-405e-b36b-01956075d52d

added cancel and returns page

---

client/package-lock.json
client/package.json
client/src/Pages/LoginPage.jsx
client/src/Pages/SignUpPage.jsx
client/src/validations/validation.js
package-lock.json
package.json

- Adds input validation
- 
- Placeholder: "Fixes #509 
- Added input validations in login and signup pages

[Feature] : Added validation for form inputs

---

client/src/Pages/Wishlist.jsx

- Fixes the issue number #542 
- updated  the dependency of useEffect hook in WhishList Screen which was causing a infinite loop. 

[Bug Fix] Fixed issue #542

---

client/src/Pages/Newarrivals.js

- Adds Google Books API so that books in the new arrivals section can be automatically updated instead of hard coding the book details.
- Fixes ...
- Updates ...
- Placeholder: "Fixes #533 "
- Added a new feature to NewArrivals.js file
Add any screenshots that …

Generate random books using Google books api in New arrivals

---

client/src/Components/NavBar/NavBar.jsx

Fixes Navbar Items text-underline properties to enhance navbar looks, and also updates the colour of the hover effect. 
#595 
https://github.com/user-attachments/assets/63ef63ac-bb63-44a3-a994-cb8c8509f0c3

[Fix]: removed underline Properties

---

client/src/Components/Footer/Footer.css

#Fixes 
#594 
https://github.com/user-attachments/assets/a7fa9e19-e8c4-4187-be76-13c0f2ffd542

[Fix]: fixes subscribe button

---

client/public/index.html
client/src/index.css

This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
Fixes: #551 

background color changed of the toggle button

---

README.md

added banners to the website
Fixes #609 
- Added banners
- [x ] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] I am working on this issue under GSSOC

ADD HACKTOBERFEST AND GSSOC BANNER ON THE README
